.TH "Compiler.Token" 3 "Sun Oct 28 2018" "Version 1.0.0" "Compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Compiler.Token
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToken\fP (\fBTokenKind\fP kind, string _Spelling, \fBSourcePosition\fP _Position)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSpelling\fP = ''\fC [get]\fP"
.br
.ti -1c
.RI "\fBTokenKind\fP \fBKind\fP = 0\fC [get]\fP"
.br
.ti -1c
.RI "\fBSourcePosition\fP \fBPosition\fP = null\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a token ans holds all the relevant information about it\&. 
.PP
\fBSee also:\fP
.RS 4
\fBTokenKind\fP 
.PP
\fBSourcePosition\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Compiler\&.Token\&.Token (\fBTokenKind\fP kind, string _Spelling, \fBSourcePosition\fP _Position)"
Builds a
.PP
.nf
Token 

.fi
.PP
 object from the given parameters\&. 
.PP
\fBParameters:\fP
.RS 4
\fIkind\fP the kind of the token 
.br
\fI_Spelling\fP the spelling of the token 
.br
\fI_Position\fP the position of the token 
.RE
.PP

.PP
.nf
34                                                                                      {
35                 Spelling = _Spelling;
36                 Kind = kind;
37                 Position = _Position;
38             }
.fi
.SH "Member Function Documentation"
.PP 
.SS "override string Compiler\&.Token\&.ToString ()"
Overrides the cast of a
.PP
.nf
Token 

.fi
.PP
 object to a
.PP
.nf
string 

.fi
.PP
 \&. 
.PP
.nf
42 { return string\&.Format($"{Position\&.ToString()}-Kind = {Kind}, spelling = \"{Spelling}\""); }
.fi
.SH "Property Documentation"
.PP 
.SS "\fBTokenKind\fP Compiler\&.Token\&.Kind = 0\fC [get]\fP"
Contains the kind of the token\&. 
.PP
\fBSee also:\fP
.RS 4
\fBTokenKind\fP 
.RE
.PP

.PP
.nf
21 { get; } = 0;
.fi
.SS "\fBSourcePosition\fP Compiler\&.Token\&.Position = null\fC [get]\fP"
Contains the position of the token in the source file\&. 
.PP
\fBSee also:\fP
.RS 4
\fBSourcePosition\fP 
.RE
.PP

.PP
.nf
26 { get; } = null;
.fi
.SS "string Compiler\&.Token\&.Spelling = ''\fC [get]\fP"
Contains the spelling of the token\&. 
.PP
.nf
16 { get; } = "";
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Compiler from the source code\&.
