.TH "Compiler.SourcePosition" 3 "Sun Oct 28 2018" "Version 1.0.0" "Compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Compiler.SourcePosition
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSourcePosition\fP (\fBLocation\fP _Start, \fBLocation\fP _End)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLocation\fP \fBStart\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the start and end positions of an element in the file\&. 
.PP
\fBSee also:\fP
.RS 4
\fBLocation\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Compiler\&.SourcePosition\&.SourcePosition (\fBLocation\fP _Start, \fBLocation\fP _End)"
Builds a
.PP
.nf
SourcePosition 

.fi
.PP
 object from two
.PP
.nf
Location 

.fi
.PP
 objects\&. 
.PP
\fBParameters:\fP
.RS 4
\fI_Start\fP the start position 
.br
\fI_End\fP the end position 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override string Compiler\&.SourcePosition\&.ToString ()"
Overrides the cast of a
.PP
.nf
SourcePosition 

.fi
.PP
 object to a
.PP
.nf
string 

.fi
.PP
 \&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBLocation\fP Compiler\&.SourcePosition\&.Start = null"
Represents the start position of the element\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Compiler from the source code\&.
