.TH "Compiler.SourceFile" 3 "Sun Oct 28 2018" "Version 1.0.0" "Compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Compiler.SourceFile
.SH SYNOPSIS
.br
.PP
.PP
Inherits IEnumerator< char >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSourceFile\fP (string sourceFileName)"
.br
.ti -1c
.RI "bool \fBMoveNext\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.ti -1c
.RI "bool \fBSkipRestOfLine\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "char \fBCurrent\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP = ''\fC [get]\fP"
.br
.ti -1c
.RI "\fBLocation\fP \fB_Location\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds the source file content as a collection of characters\&. Reads the file line by line\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Compiler\&.SourceFile\&.SourceFile (string sourceFileName)"
Builds a
.PP
.nf
SourceFile 

.fi
.PP
 instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsourceFileName\fP string representing the file name of the file to open\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Compiler\&.SourceFile\&.Dispose ()"
Destroys the current object\&. 
.PP
\fBDeprecated\fP
.RS 4

.RE
.PP

.SS "virtual void Compiler\&.SourceFile\&.Dispose (bool disposing)\fC [protected]\fP, \fC [virtual]\fP"
Destroys the
.PP
.nf
StreamReader 

.fi
.PP
 if the source is not
.PP
.nf
null 

.fi
.PP
 \&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP If this variable is set to
.PP
.nf
false 

.fi
.PP
 , the
.PP
.nf
StreamReader 

.fi
.PP
 will not be destroyed\&. 
.RE
.PP

.SS "bool Compiler\&.SourceFile\&.MoveNext ()"
Moves the index to the next character\&. If the index has reached the end of the line, a new line is read\&. 
.PP
\fBReturns:\fP
.RS 4

.PP
.nf
true 

.fi
.PP
 if the buffer is not full,
.PP
.nf
false 

.fi
.PP
 otherwise\&. 
.RE
.PP

.SS "void Compiler\&.SourceFile\&.Reset ()"
Resets the reading of the source code file\&. 
.PP
\fBExceptions:\fP
.RS 4
\fIInvalidOperationException\fP This exception is thrown if the source code file is
.PP
.nf
null 

.fi
.PP
 \&. 
.br
\fINotSupportedException\fP This exception is thrown to mark the seeking of the current stream as not supported yet\&. 
.RE
.PP

.SS "bool Compiler\&.SourceFile\&.SkipRestOfLine ()"
Destroys the current object\&. 
.PP
\fBReturns:\fP
.RS 4
If the end of the file has been reached, returns
.PP
.nf
true 

.fi
.PP
 , otherwise
.PP
.nf
false 

.fi
.PP
 \&. 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBLocation\fP Compiler\&.SourceFile\&._Location\fC [get]\fP"
\fBLocation\fP of the current character in the file\&. 
.SS "char Compiler\&.SourceFile\&.Current\fC [get]\fP"
Last character of the buffer, if the buffer is not
.PP
.nf
null 

.fi
.PP
 \&. 
.SS "string Compiler\&.SourceFile\&.Name = ''\fC [get]\fP"
Name of the souce code file\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Compiler from the source code\&.
