.TH "D:/Users/i/Desktop/LanguagesAndCompilersCoursework/Compiler/obj/Debug Directory Reference" 3 "Sun Oct 28 2018" "Version 1.0.0" "Compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Users/i/Desktop/LanguagesAndCompilersCoursework/Compiler/obj/Debug Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBnetcoreapp2\&.2\fP"
.br
.in -1c
