.TH "D:/Users/i/Desktop/LanguagesAndCompilersCoursework/Compiler/Scanner.cs" 3 "Sun Oct 28 2018" "Version 1.0.0" "Compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Users/i/Desktop/LanguagesAndCompilersCoursework/Compiler/Scanner.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompiler\&.Scanner\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCompiler\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Compiler from the source code\&.
